site_name: 24/7 Online AA Meeting on Zoom | 24 Hour International Marathon Meeting of AA
site_description: Join a live 24/7 Online AA Meeting on Zoom. Open international Alcoholics Anonymous fellowship. Meeting ID 292 371 2604. No password required.
site_author: Help 24/7
site_url: https://sobrietyneversleeps.org/

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: default
      primary: indigo
      accent: blue
  features:
    - navigation.instant
    - content.code.copy

extra_css:
  - stylesheets/extra.css
